name: FreeElytra
version: 1.0-Beta
main: de.blaumeise03.freeElytra.FreeElytra
api-version: 1.13
author: Blaumeise03
website: http://blaumeise03.de/

commands:
  elytra:
    description: Gibt dir eine Kostenlose Elytra (ein Flug)
    permission: freeElytra.elytra
  addPad:
    description: Fügt ein StartPad hinzu.
    permission: freeElytra.settings
  removePad:
    description: Löscht ein StartPad.
    permission: freeElytra.settings
  listPads:
    description: Listet alle Pads auf.
    permission: freeElytra.settings
permissions:
  freeElytra.elytra:
    description: Permission for Getting an Elytra
    default: op
  freeElytra.*:
    description: Wildcard permission
    children:
      freeElytra.elytra: true
      freeElytra.settings: true
  freeElytra.settings:
    description: Change Settings of FreeElytra
    default: op