name: FreeElytra
version: 1.0-Beta
main: de.blaumeise03.freeElytra.FreeElytra
author: Blaumeise03

commands:
  elytra:
    description: Gibt dir eine Kostenlose Elytra (ein Flug)
  addPad:
    description: Fügt ein StartPad hinzu.
  removePad:
    description: Löscht ein StartPad.
  listPads:
    description: Listet alle Pads auf.
permissions:
  freeElytra.elytra:
    description: Permission for Getting an Elytra
    default: op
  freeElytra.*:
    description: Wildcard permission
    children:
      freeElytra.elytra: true
      freeElytra.settings: true
  freeElytra.settings:
    description: Change Settings of FreeElytra
    default: op